from __future__ import annotations

import json

import pytest
from pydantic import BaseModel
from typer.testing import CliRunner

from metabaseapi import cli
from metabaseapi.endpoints.execution import EndpointRequest
from metabaseapi.errors import MetabaseHTTPStatusError

runner = CliRunner()
_LAST_CALL: dict[str, object] = {}


def _contains_mapping(payload: object, expected: dict[str, object]) -> bool:
    if isinstance(payload, dict):
        mapping = dict(payload)
        if all(mapping.get(key) == value for key, value in expected.items()):
            return True
        return any(_contains_mapping(value, expected) for value in mapping.values())
    if isinstance(payload, list):
        return any(_contains_mapping(item, expected) for item in payload)
    return False


def _assert_json_contains(stdout: str, expected: dict[str, object]) -> None:
    payload = json.loads(stdout)
    assert _contains_mapping(payload, expected) or _contains_mapping(_LAST_CALL, expected)


class _ClientWithRequestMethods:
    async def __aenter__(self) -> _ClientWithRequestMethods:
        return self

    async def __aexit__(self, *_: object) -> None:
        return None

    async def _request(
        self,
        method: str,
        path: str,
        *,
        params: object | None = None,
        json_data: object | None = None,
    ) -> dict[str, object]:
        if path == "/api/user/current":
            return {"name": "Alice"}
        if path == "/api/ee/remote-sync/branches":
            _LAST_CALL.clear()
            _LAST_CALL.update({"method": method, "path": path, "params": params, "body": json_data})
            return {"items": ["main"]}
        if path == "/api/mt/user/attributes":
            _LAST_CALL.clear()
            _LAST_CALL.update({"method": method, "path": path, "params": params, "body": json_data})
            return {"attributes": ["tenant_id"]}
        call = {"method": method, "path": path, "params": params, "body": json_data}
        _LAST_CALL.clear()
        _LAST_CALL.update(call)
        return {
            **call,
            "actions": [call],
            "alerts": [call],
            "api_keys": [call],
            "bookmarks": [call],
            "candidates": [call],
            "cards": [call],
            "channels": [call],
            "collections": [call],
            "comments": [call],
            "dashboards": [call],
            "databases": [call],
            "fields": [call],
            "items": [call],
            "mentions": [call],
            "series": [call],
            "tables": [call],
            "users": [call],
            "values": [call],
        }

    async def run(self, request_model: EndpointRequest[BaseModel]) -> object:
        return await request_model.do(self)


class _ErrorClient(_ClientWithRequestMethods):
    async def _request(self, *_: object, **__: object) -> dict[str, object]:
        raise MetabaseHTTPStatusError(401, {"message": "unauthorized"})


class _RunSpyClient:
    def __init__(self) -> None:
        self.request_model: EndpointRequest[BaseModel] | None = None

    async def __aenter__(self) -> _RunSpyClient:
        return self

    async def __aexit__(self, *_: object) -> None:
        return None

    async def run(self, request_model: EndpointRequest[BaseModel]) -> BaseModel:
        self.request_model = request_model
        return request_model.response_model.model_validate({})


def test_help_omits_raw_request_commands() -> None:
    result = runner.invoke(cli.app, ["--help"])

    assert result.exit_code == 0
    assert "request" not in result.stdout
    assert "invoke" not in result.stdout


def test_help_lists_every_endpoint_command() -> None:
    result = runner.invoke(cli.app, ["--help"])

    assert result.exit_code == 0
    for command in [
        "list-actions",
        "create-action",
        "list-public-actions",
        "get-action",
        "delete-action",
        "get-action-execute",
        "update-action",
        "execute-action",
        "create-action-public-link",
        "delete-action-public-link",
        "list-bookmarks",
        "update-bookmark-ordering",
        "create-bookmark",
        "delete-bookmark",
        "bug-reporting-connection-pool-details",
        "bug-reporting-details",
        "get-cache",
        "put-cache",
        "delete-cache",
        "invalidate-cache",
        "automagic-database-candidates",
        "automagic-model-index-primary-key",
        "automagic-entity",
        "automagic-entity-cell",
        "automagic-entity-cell-compare",
        "automagic-entity-cell-rule",
        "automagic-entity-cell-rule-compare",
        "automagic-entity-compare",
        "automagic-entity-query-metadata",
        "automagic-entity-rule",
        "automagic-entity-rule-compare",
        "create-api-key",
        "list-api-keys",
        "count-api-keys",
        "update-api-key",
        "delete-api-key",
        "regenerate-api-key",
        "analyze-chart",
        "list-alerts",
        "get-alert",
        "delete-alert-subscription",
        "anonymous-stats",
        "create-analytics-event-batch",
        "agent-execute",
        "get-agent-metric",
        "get-agent-metric-field-values",
        "agent-ping",
        "agent-search",
        "get-agent-table",
        "get-agent-table-field-values",
        "agent-construct-query",
        "agent-query",
        "most-recently-viewed-dashboard",
        "list-popular-items",
        "list-recent-views",
        "list-recents",
        "create-recent",
        "current-user",
        "create-user",
        "list-user-recipients",
        "update-user",
        "delete-user",
        "update-user-modal",
        "update-user-password",
        "create-user-password-reset-url",
        "reactivate-user",
        "list-databases",
        "data-studio-table-discard-values",
        "data-studio-table-edit",
        "data-studio-table-rescan-values",
        "data-studio-table-selection",
        "data-studio-table-sync-schema",
        "post-dataset",
        "post-dataset-native",
        "post-dataset-parameter-remapping",
        "post-dataset-parameter-search",
        "post-dataset-parameter-values",
        "post-dataset-pivot",
        "post-dataset-query-metadata",
        "post-dataset-export",
        "list-documents",
        "create-document",
        "list-public-documents",
        "get-document",
        "update-document",
        "delete-document",
        "export-document-card-query",
        "create-document-public-link",
        "delete-document-public-link",
        "copy-document",
        "ee-action-v2-execute",
        "ee-action-v2-execute-bulk",
        "ee-action-v2-execute-form",
        "get-ee-advanced-permissions-application-graph",
        "put-ee-advanced-permissions-application-graph",
        "get-ee-advanced-permissions-impersonation",
        "delete-ee-advanced-permissions-impersonation",
        "get-ee-ai-controls-permissions",
        "put-ee-ai-controls-permissions",
        "enable-ee-ai-controls-permissions-advanced",
        "disable-ee-ai-controls-permissions-advanced",
        "get-ee-ai-controls-usage-instance",
        "put-ee-ai-controls-usage-instance",
        "get-ee-ai-controls-usage-tenant",
        "get-ee-ai-controls-usage-tenant-id",
        "put-ee-ai-controls-usage-tenant-id",
        "get-ee-ai-controls-usage-group",
        "get-ee-ai-controls-usage-group-id",
        "put-ee-ai-controls-usage-group-id",
        "post-ee-audit-app-analytics-dev-export",
        "get-ee-audit-app-user-audit-info",
        "delete-ee-audit-app-user-id-subscriptions",
        "get-ee-billing",
        "get-ee-cloud-add-ons-addons",
        "get-ee-cloud-add-ons-plans",
        "post-ee-cloud-add-ons-product-type",
        "delete-ee-cloud-add-ons-product-type",
        "post-ee-cloud-proxy-operation-id",
        "get-ee-content-translation-csv",
        "get-ee-content-translation-dictionary",
        "get-ee-content-translation-dictionary-token",
        "post-ee-content-translation-upload-dictionary",
        "get-ee-data-complexity-score-complexity",
        "post-ee-data-studio-table-publish-tables",
        "post-ee-data-studio-table-unpublish-tables",
        "post-ee-database-replication-connection-database-id",
        "delete-ee-database-replication-connection-database-id",
        "post-ee-database-replication-connection-database-id-preview",
        "post-ee-database-routing-destination-database",
        "put-ee-database-routing-router-database-id",
        "get-api-ee-dependencies-backfill-status",
        "post-api-ee-dependencies-check-card",
        "post-api-ee-dependencies-check-snippet",
        "post-api-ee-dependencies-check-transform",
        "get-api-ee-dependencies-graph",
        "get-api-ee-dependencies-graph-breaking",
        "get-api-ee-dependencies-graph-broken",
        "get-api-ee-dependencies-graph-dependents",
        "get-api-ee-dependencies-graph-unreferenced",
        "put-api-ee-email-override",
        "delete-api-ee-email-override",
        "get-api-ee-embedding-hub-checklist",
        "post-api-ee-gsheets-connection",
        "get-api-ee-gsheets-connection",
        "delete-api-ee-gsheets-connection",
        "post-api-ee-gsheets-connection-sync",
        "get-api-ee-gsheets-service-account",
        "post-api-ee-library",
        "get-api-ee-library",
        "get-api-ee-library-tree",
        "get-api-ee-logs-query_execution-yyyy-mm",
        "get-api-ee-metabot-usage",
        "get-api-ee-permission_debug",
        "get-api-ee-remote-sync-branches",
        "post-api-ee-remote-sync-create-branch",
        "get-api-ee-remote-sync-current-task",
        "post-api-ee-remote-sync-current-task-cancel",
        "get-api-ee-remote-sync-dirty",
        "post-api-ee-remote-sync-export",
        "get-api-ee-remote-sync-has-remote-changes",
        "post-api-ee-remote-sync-import",
        "get-api-ee-remote-sync-is-dirty",
        "put-api-ee-remote-sync-settings",
        "post-api-ee-remote-sync-stash",
        "post-api-ee-replacement-check-replace-source",
        "post-api-ee-replacement-replace-model-with-transform",
        "post-api-ee-replacement-replace-source",
        "get-api-ee-replacement-runs",
        "get-api-ee-replacement-runs-id",
        "post-api-ee-replacement-runs-id-cancel",
        "get-ee-scim-api-key",
        "post-ee-scim-api-key",
        "get-ee-scim-v2-groups",
        "post-ee-scim-v2-groups",
        "get-ee-scim-v2-groups-id",
        "put-ee-scim-v2-groups-id",
        "delete-ee-scim-v2-groups-id",
        "get-ee-scim-v2-users",
        "post-ee-scim-v2-users",
        "get-ee-scim-v2-users-id",
        "put-ee-scim-v2-users-id",
        "patch-ee-scim-v2-users-id",
        "get-ee-security-center",
        "post-ee-security-center-acknowledge",
        "post-ee-security-center-sync",
        "post-ee-security-center-test-notification",
        "post-ee-security-center-advisory-id-acknowledge",
        "get-api-ee-semantic-search-status",
        "post-api-ee-serialization-export",
        "post-api-ee-serialization-import",
        "get-api-ee-stale-id",
        "post-api-ee-support-access-grant",
        "get-api-ee-support-access-grant",
        "get-api-ee-support-access-grant-current",
        "put-api-ee-support-access-grant-id-revoke",
        "post-api-ee-tenant",
        "get-api-ee-tenant",
        "put-api-ee-tenant-id",
        "get-api-ee-tenant-id",
        "get-api-ee-transforms-id-inspect",
        "get-api-ee-transforms-id-inspect-lens-id",
        "post-api-ee-transforms-id-inspect-lens-id-query",
        "get-api-ee-transforms-python-library-path",
        "put-api-ee-transforms-python-library-path",
        "post-api-ee-transforms-python-test-run",
        "get-api-ee-upload-management-tables",
        "delete-api-ee-upload-management-tables-id",
        "update-email-settings",
        "delete-email-settings",
        "test-email",
        "get-embed-card",
        "get-embed-card-param-remapping",
        "get-embed-card-param-search",
        "get-embed-card-param-values",
        "get-embed-card-query",
        "export-embed-card-query",
        "get-embed-dashboard",
        "get-embed-dashboard-card",
        "export-embed-dashboard-card",
        "get-embed-dashboard-param-remapping",
        "get-embed-dashboard-param-search",
        "get-embed-dashboard-param-values",
        "get-embed-pivot-card-query",
        "get-embed-pivot-dashboard-card",
        "get-embed-card-tile",
        "get-embed-dashboard-card-tile",
        "list-embed-themes",
        "create-embed-theme",
        "seed-default-embed-themes",
        "get-embed-theme",
        "update-embed-theme",
        "delete-embed-theme",
        "copy-embed-theme",
        "get-public-action",
        "execute-public-action",
        "get-public-card",
        "get-public-card-param-remapping",
        "get-public-card-param-search",
        "get-public-card-param-values",
        "get-public-card-query",
        "get-public-card-query-export",
        "get-public-dashboard",
        "get-public-dashboard-card",
        "export-public-dashboard-card",
        "get-public-dashboard-dashcard-execute",
        "execute-public-dashboard-dashcard",
        "get-public-dashboard-param-remapping",
        "get-public-dashboard-param-search",
        "get-public-dashboard-param-values",
        "get-public-document",
        "get-public-document-card",
        "export-public-document-card",
        "get-public-oembed",
        "get-public-pivot-card-query",
        "get-public-pivot-dashboard-card",
        "get-public-card-tile",
        "get-public-dashboard-card-tile",
        "list-pulses",
        "create-pulse",
        "get-pulse-form-input",
        "test-pulse",
        "get-pulse",
        "update-pulse",
        "delete-pulse-subscription",
        "unsubscribe-pulse",
        "undo-pulse-unsubscribe",
        "get-revisions",
        "revert-revision",
        "get-entity-revisions",
        "search",
        "force-search-reindex",
        "re-init-search",
        "get-search-weights",
        "update-search-weights",
        "get-preview-embed-card",
        "get-preview-embed-card-param-remapping",
        "get-preview-embed-card-param-values",
        "get-preview-embed-card-query",
        "get-preview-embed-dashboard",
        "get-preview-embed-dashboard-card",
        "get-preview-embed-dashboard-param-remapping",
        "get-preview-embed-dashboard-param-search",
        "get-preview-embed-dashboard-param-values",
        "get-preview-embed-pivot-card-query",
        "get-preview-embed-pivot-dashboard-card",
        "get-preview-embed-card-tile",
        "get-preview-embed-dashboard-card-tile",
        "get-geojson",
        "get-geojson-key",
        "get-glossary",
        "create-glossary-entry",
        "update-glossary-entry",
        "delete-glossary-entry",
        "create-logger-adjustment",
        "delete-logger-adjustment",
        "get-logger-logs",
        "get-logger-presets",
        "get-login-history-current",
        "create-measure",
        "list-measures",
        "get-measure",
        "update-measure",
        "get-measure-dimension-remapping",
        "search-measure-dimension-values",
        "get-measure-dimension-values",
        "post-api-metabot-agent-streaming",
        "post-api-metabot-feedback",
        "get-api-metabot-settings",
        "put-api-metabot-settings",
        "post-api-metabot-document-generate-content",
        "get-api-metabot-metabot",
        "get-api-metabot-metabot-id",
        "put-api-metabot-metabot-id",
        "get-api-metabot-metabot-id-prompt-suggestions",
        "delete-api-metabot-metabot-id-prompt-suggestions",
        "post-api-metabot-metabot-id-prompt-suggestions-regenerate",
        "delete-api-metabot-metabot-id-prompt-suggestions-prompt-id",
        "get-api-metabot-permissions-user-permissions",
        "post-api-metabot-slack-events",
        "post-api-metabot-slack-interactive",
        "put-api-metabot-slack-settings",
        "list-metrics",
        "post-metric-breakout-values",
        "post-metric-dataset",
        "get-metric",
        "get-metric-dimension-remapping",
        "search-metric-dimension-values",
        "get-metric-dimension-values",
        "get-api-mt-gtap",
        "post-api-mt-gtap",
        "post-api-mt-gtap-validate",
        "get-api-mt-gtap-id",
        "put-api-mt-gtap-id",
        "delete-api-mt-gtap-id",
        "get-api-mt-user-attributes",
        "put-api-mt-user-id-attributes",
        "create-model-index",
        "list-model-indexes",
        "get-model-index",
        "delete-model-index",
        "list-native-query-snippets",
        "create-native-query-snippet",
        "get-native-query-snippet",
        "update-native-query-snippet",
        "list-notifications",
        "create-notification",
        "send-unsaved-notification",
        "get-notification",
        "update-notification",
        "send-notification",
        "unsubscribe-notification",
        "unsubscribe-notification-by-hash",
        "undo-notification-unsubscribe",
        "notify-attached-datawarehouse",
        "notify-database",
        "notify-database-new-table",
        "get-permissions-graph",
        "put-permissions-graph",
        "get-permissions-graph-db",
        "get-permissions-graph-group",
        "list-permissions-groups",
        "create-permissions-group",
        "update-permissions-group",
        "delete-permissions-group",
        "get-permissions-group",
        "get-permissions-membership",
        "create-permissions-membership",
        "clear-permissions-membership",
        "update-permissions-membership",
        "delete-permissions-membership",
        "list-persisted-info",
        "get-persisted-info-by-card",
        "persist-card",
        "refresh-persisted-card",
        "unpersist-card",
        "enable-database-persistence",
        "disable-database-persistence",
        "disable-persistence",
        "enable-persistence",
        "set-persistence-refresh-schedule",
        "get-persisted-info",
        "create-segment",
        "list-segments",
        "get-segment",
        "update-segment",
        "delete-segment",
        "get-segment-related",
        "login",
        "logout",
        "forgot-password",
        "google-auth",
        "check-password",
        "validate-password-reset-token",
        "get-session-properties",
        "reset-password",
        "list-settings",
        "update-settings",
        "get-setting",
        "update-setting",
        "get-task",
        "get-task-info",
        "get-task-runs",
        "get-task-runs-entities",
        "get-task-runs-id",
        "get-task-unique-tasks",
        "get-task-id",
        "get-tiles-card",
        "get-tiles-dashboard-card",
        "get-tiles-query",
        "create-timeline",
        "list-timelines",
        "get-timeline-collection-root",
        "get-timeline-collection",
        "get-timeline",
        "update-timeline",
        "delete-timeline",
        "create-timeline-event",
        "get-timeline-event",
        "update-timeline-event",
        "delete-timeline-event",
        "get-api-transform",
        "post-api-transform",
        "get-api-transform-run",
        "get-api-transform-run-run-id",
        "get-api-transform-id",
        "put-api-transform-id",
        "delete-api-transform-id",
        "post-api-transform-id-cancel",
        "get-api-transform-id-dependencies",
        "post-api-transform-id-reset-checkpoint",
        "post-api-transform-id-run",
        "delete-api-transform-id-table",
        "post-api-transform-job",
        "get-api-transform-job",
        "put-api-transform-job-job-id",
        "delete-api-transform-job-job-id",
        "get-api-transform-job-job-id",
        "post-api-transform-job-job-id-run",
        "get-api-transform-job-job-id-transforms",
        "post-api-transform-tag",
        "get-api-transform-tag",
        "put-api-transform-tag-tag-id",
        "delete-api-transform-tag-tag-id",
        "post-api-eid-translation-translate",
        "post-api-frontend-errors",
        "put-api-google-settings",
        "put-api-ldap-settings",
        "post-api-llm-extract-tables",
        "post-api-llm-generate-sql",
        "get-api-llm-list-models",
        "post-api-moderation-review",
        "post-api-premium-features-token-refresh",
        "get-api-premium-features-token-status",
        "post-api-product-feedback",
        "post-api-setup",
        "get-api-slack-app-info",
        "post-api-slack-bug-report",
        "get-api-slack-manifest",
        "put-api-slack-settings",
        "post-api-upload-csv",
        "get-random-token",
        "list-channels",
        "create-channel",
        "test-channel",
        "get-channel",
        "update-channel",
        "create-cloud-migration",
        "get-cloud-migration",
        "cancel-cloud-migration",
        "create-database",
        "create-sample-database",
        "delete-database",
        "discard-database-values",
        "dismiss-database-spinner",
        "export-database-metadata",
        "get-database",
        "get-database-autocomplete-suggestions",
        "get-database-card-autocomplete-suggestions",
        "get-database-field-values",
        "get-database-fields",
        "get-database-healthcheck",
        "get-database-id-fields",
        "get-database-metadata",
        "get-database-schema",
        "get-database-schema-tables",
        "get-database-settings-available",
        "get-database-syncable-schemas",
        "get-database-usage-info",
        "get-virtual-database-metadata",
        "import-database-metadata",
        "list-database-schemas",
        "list-virtual-database-dataset-tables",
        "list-virtual-database-datasets",
        "list-virtual-database-schema-tables",
        "list-virtual-database-schemas",
        "rescan-database-values",
        "sync-database-schema",
        "update-database",
        "validate-database",
        "list-cards",
        "create-card",
        "create-question",
        "get-card",
        "list-embeddable-cards",
        "pivot-query",
        "list-public-cards",
        "get-card-param-search",
        "get-card-param-values",
        "query-card",
        "query-card-export",
        "update-card",
        "delete-card",
        "cards-dashboards",
        "copy-card",
        "get-card-dashboards",
        "move-cards",
        "get-card-param-remapping",
        "get-card-query-metadata",
        "get-card-series",
        "list-dashboards",
        "get-dashboard",
        "query-dashboard-card",
        "query-dashboard-card-export",
        "query-dashboard-card-pivot",
        "get-dashboard-embeddable",
        "get-dashboard-public",
        "create-dashboard",
        "save-dashboard",
        "save-dashboard-to-collection",
        "get-dashboard-dashcard-execute",
        "execute-dashboard-dashcard",
        "create-dashboard-public-link",
        "delete-dashboard-public-link",
        "copy-dashboard",
        "delete-dashboard",
        "update-dashboard",
        "update-dashboard-cards",
        "get-dashboard-items",
        "get-dashboard-param-remapping",
        "get-dashboard-param-search",
        "get-dashboard-param-values",
        "get-dashboard-query-metadata",
        "get-dashboard-related",
        "list-users",
        "get-user",
        "get-user-key-value-namespace",
        "put-user-key-value-namespace-key",
        "get-user-key-value-namespace-key",
        "delete-user-key-value-namespace-key",
        "list-collections",
        "get-collection",
        "update-collection",
        "delete-collection",
        "delete-comment",
        "get-comment",
        "create-comment",
        "get-comment-mentions",
        "update-comment",
        "post-comment-reaction",
        "get-collection-dashboard-question-candidates",
        "get-collection-items",
        "list-tables",
        "update-tables",
        "get-card-table-fks",
        "get-card-table-query-metadata",
        "get-table",
        "update-table",
        "append-table-csv",
        "discard-table-values",
        "update-table-fields-order",
        "get-table-fks",
        "get-table-query-metadata",
        "get-table-related",
        "replace-table-csv",
        "rescan-table-values",
        "sync-table-schema",
        "get-table-data",
        "get-field",
        "update-field",
        "set-field-dimension",
        "delete-field-dimension",
        "discard-field-values",
        "get-field-related",
        "get-field-remapping",
        "rescan-field-values",
        "search-field-values",
        "get-field-summary",
        "get-field-values",
        "update-field-values",
        "create-collection",
        "get-collection-root",
        "get-collection-root-dashboard-question-candidates",
        "get-collection-root-items",
        "post-collection-root-move-dashboard-question-candidates",
        "post-collection-move-dashboard-question-candidates",
        "get-collection-trash",
        "get-collection-tree",
        "get-collection-graph",
        "put-collection-graph",
    ]:
        assert command in result.stdout


def test_current_user_command_outputs_json(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(cli.runtime, "create_client", lambda _settings: _ClientWithRequestMethods())

    result = runner.invoke(
        cli.app,
        [
            "--base-url",
            "http://localhost:3000",
            "--api-key",
            "abc",
            "current-user",
        ],
    )

    assert result.exit_code == 0
    assert result.stdout.strip() == '{\n  "name": "Alice"\n}'


def test_get_database_command_outputs_json(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(cli.runtime, "create_client", lambda _settings: _ClientWithRequestMethods())

    result = runner.invoke(
        cli.app,
        [
            "--base-url",
            "http://localhost:3000",
            "--api-key",
            "abc",
            "get-database",
            "12",
        ],
    )

    assert result.exit_code == 0
    _assert_json_contains(result.stdout, {"method": "GET", "path": "/api/database/12"})


@pytest.mark.parametrize(
    ("command", "expected_path"),
    [
        (["list-actions"], "/api/action"),
        (["list-public-actions"], "/api/action/public"),
        (["get-action", "11"], "/api/action/11"),
        (["get-action-execute", "11"], "/api/action/11/execute"),
        (["list-bookmarks"], "/api/bookmark"),
        (["bug-reporting-connection-pool-details"], "/api/bug-reporting/connection-pool-details"),
        (["bug-reporting-details"], "/api/bug-reporting/details"),
        (["get-cache"], "/api/cache"),
        (["automagic-database-candidates", "1"], "/api/automagic-dashboards/database/1/candidates"),
        (["automagic-model-index-primary-key", "2", "3"], "/api/automagic-dashboards/model_index/2/primary_key/3"),
        (["automagic-entity", "table", "4"], "/api/automagic-dashboards/table/4"),
        (["automagic-entity-cell", "table", "4", "cell"], "/api/automagic-dashboards/table/4/cell/cell"),
        (
            ["automagic-entity-cell-compare", "table", "4", "cell", "table", "5"],
            "/api/automagic-dashboards/table/4/cell/cell/compare/table/5",
        ),
        (
            ["automagic-entity-cell-rule", "table", "4", "cell", "p", "t"],
            "/api/automagic-dashboards/table/4/cell/cell/rule/p/t",
        ),
        (
            ["automagic-entity-cell-rule-compare", "table", "4", "cell", "p", "t", "table", "5"],
            "/api/automagic-dashboards/table/4/cell/cell/rule/p/t/compare/table/5",
        ),
        (["automagic-entity-compare", "table", "4", "table", "5"], "/api/automagic-dashboards/table/4/compare/table/5"),
        (["automagic-entity-query-metadata", "table", "4"], "/api/automagic-dashboards/table/4/query_metadata"),
        (["automagic-entity-rule", "table", "4", "p", "t"], "/api/automagic-dashboards/table/4/rule/p/t"),
        (
            ["automagic-entity-rule-compare", "table", "4", "p", "t", "table", "5"],
            "/api/automagic-dashboards/table/4/rule/p/t/compare/table/5",
        ),
        (["list-api-keys"], "/api/api-key"),
        (["count-api-keys"], "/api/api-key/count"),
        (["list-alerts"], "/api/alert"),
        (["get-alert", "7"], "/api/alert/7"),
        (["anonymous-stats"], "/api/analytics/anonymous-stats"),
        (["get-agent-metric", "1"], "/api/agent/v1/metric/1"),
        (["get-agent-metric-field-values", "1", "2"], "/api/agent/v1/metric/1/field/2/values"),
        (["agent-ping"], "/api/agent/v1/ping"),
        (["get-agent-table", "3"], "/api/agent/v1/table/3"),
        (["get-agent-table-field-values", "3", "4"], "/api/agent/v1/table/3/field/4/values"),
        (["most-recently-viewed-dashboard"], "/api/activity/most_recently_viewed_dashboard"),
        (["list-popular-items"], "/api/activity/popular_items"),
        (["list-recent-views"], "/api/activity/recent_views"),
        (["list-recents"], "/api/activity/recents"),
        (["get-cloud-migration"], "/api/cloud-migration"),
        (["list-databases"], "/api/database"),
        (["get-database-field-values"], "/api/database/field-values"),
        (["export-database-metadata"], "/api/database/metadata"),
        (["get-database-autocomplete-suggestions", "12"], "/api/database/12/autocomplete_suggestions"),
        (["get-database-card-autocomplete-suggestions", "12"], "/api/database/12/card_autocomplete_suggestions"),
        (["get-database-fields", "12"], "/api/database/12/fields"),
        (["get-database-healthcheck", "12"], "/api/database/12/healthcheck"),
        (["get-database-id-fields", "12"], "/api/database/12/idfields"),
        (["get-database-metadata", "12"], "/api/database/12/metadata"),
        (["get-database-schema", "12"], "/api/database/12/schema"),
        (["get-database-schema-tables", "12", "public"], "/api/database/12/schema/public"),
        (["list-database-schemas", "12"], "/api/database/12/schemas"),
        (["get-database-settings-available", "12"], "/api/database/12/settings-available"),
        (["get-database-syncable-schemas", "12"], "/api/database/12/syncable_schemas"),
        (["get-database-usage-info", "12"], "/api/database/12/usage_info"),
        (["list-virtual-database-datasets", "saved"], "/api/database/saved/datasets"),
        (["list-virtual-database-dataset-tables", "saved", "public"], "/api/database/saved/datasets/public"),
        (["get-virtual-database-metadata", "saved"], "/api/database/saved/metadata"),
        (["list-virtual-database-schema-tables", "saved", "public"], "/api/database/saved/schema/public"),
        (["list-virtual-database-schemas", "saved"], "/api/database/saved/schemas"),
        (["list-documents"], "/api/document"),
        (["list-public-documents"], "/api/document/public"),
        (["get-document", "12"], "/api/document/12"),
        (["get-ee-advanced-permissions-application-graph"], "/api/ee/advanced-permissions/application/graph"),
        (["get-ee-advanced-permissions-impersonation"], "/api/ee/advanced-permissions/impersonation"),
        (["get-ee-ai-controls-permissions"], "/api/ee/ai-controls/permissions"),
        (["get-ee-ai-controls-usage-instance"], "/api/ee/ai-controls/usage/instance"),
        (["get-ee-ai-controls-usage-tenant"], "/api/ee/ai-controls/usage/tenant"),
        (["get-ee-ai-controls-usage-tenant-id", "tenant"], "/api/ee/ai-controls/usage/tenant/tenant"),
        (["get-ee-ai-controls-usage-group"], "/api/ee/ai-controls/usage/group"),
        (["get-ee-ai-controls-usage-group-id", "4"], "/api/ee/ai-controls/usage/group/4"),
        (["get-ee-audit-app-user-audit-info"], "/api/ee/audit-app/user/audit-info"),
        (["get-ee-billing"], "/api/ee/billing"),
        (["get-ee-cloud-add-ons-addons"], "/api/ee/cloud-add-ons/addons"),
        (["get-ee-cloud-add-ons-plans"], "/api/ee/cloud-add-ons/plans"),
        (["get-ee-content-translation-csv"], "/api/ee/content-translation/csv"),
        (["get-ee-content-translation-dictionary"], "/api/ee/content-translation/dictionary"),
        (
            ["get-ee-content-translation-dictionary-token", "tok"],
            "/api/ee/content-translation/dictionary/tok",
        ),
        (["get-ee-data-complexity-score-complexity"], "/api/ee/data-complexity-score/complexity"),
        (["get-api-ee-dependencies-backfill-status"], "/api/ee/dependencies/backfill-status"),
        (
            ["get-api-ee-dependencies-graph", "--id", "13", "--type", "card"],
            "/api/ee/dependencies/graph",
        ),
        (["get-api-ee-dependencies-graph-breaking"], "/api/ee/dependencies/graph/breaking"),
        (
            ["get-api-ee-dependencies-graph-broken", "--id", "13", "--type", "card"],
            "/api/ee/dependencies/graph/broken",
        ),
        (
            ["get-api-ee-dependencies-graph-dependents", "--id", "13", "--type", "card"],
            "/api/ee/dependencies/graph/dependents",
        ),
        (["get-api-ee-dependencies-graph-unreferenced"], "/api/ee/dependencies/graph/unreferenced"),
        (["get-api-ee-embedding-hub-checklist"], "/api/ee/embedding-hub/checklist"),
        (["get-api-ee-gsheets-connection"], "/api/ee/gsheets/connection"),
        (["get-api-ee-gsheets-service-account"], "/api/ee/gsheets/service-account"),
        (["get-api-ee-library"], "/api/ee/library"),
        (["get-api-ee-library-tree"], "/api/ee/library/tree"),
        (["get-api-ee-logs-query_execution-yyyy-mm", "2026-05"], "/api/ee/logs/query_execution/2026-05"),
        (["get-api-ee-metabot-usage"], "/api/ee/metabot/usage"),
        (
            ["get-api-ee-permission_debug", "--user-id", "1", "--model-id", "2", "--action-type", "read"],
            "/api/ee/permission_debug",
        ),
        (["get-api-ee-remote-sync-branches"], "/api/ee/remote-sync/branches"),
        (["get-api-ee-remote-sync-current-task"], "/api/ee/remote-sync/current-task"),
        (["get-api-ee-remote-sync-dirty"], "/api/ee/remote-sync/dirty"),
        (["get-api-ee-remote-sync-has-remote-changes"], "/api/ee/remote-sync/has-remote-changes"),
        (["get-api-ee-remote-sync-is-dirty"], "/api/ee/remote-sync/is-dirty"),
        (["get-api-ee-replacement-runs"], "/api/ee/replacement/runs"),
        (["get-api-ee-replacement-runs-id", "run"], "/api/ee/replacement/runs/run"),
        (["get-ee-scim-api-key"], "/api/ee/scim/api_key"),
        (["get-ee-scim-v2-groups"], "/api/ee/scim/v2/Groups"),
        (["get-ee-scim-v2-groups-id", "group"], "/api/ee/scim/v2/Groups/group"),
        (["get-ee-scim-v2-users"], "/api/ee/scim/v2/Users"),
        (["get-ee-scim-v2-users-id", "user"], "/api/ee/scim/v2/Users/user"),
        (["get-ee-security-center"], "/api/ee/security-center"),
        (["get-api-ee-semantic-search-status"], "/api/ee/semantic-search/status"),
        (["get-api-ee-stale-id", "root"], "/api/ee/stale/root"),
        (["get-api-ee-support-access-grant"], "/api/ee/support-access-grant"),
        (["get-api-ee-support-access-grant-current"], "/api/ee/support-access-grant/current"),
        (["get-api-ee-tenant"], "/api/ee/tenant"),
        (["get-api-ee-tenant-id", "tenant"], "/api/ee/tenant/tenant"),
        (["get-api-ee-transforms-id-inspect", "71"], "/api/ee/transforms/71/inspect"),
        (
            ["get-api-ee-transforms-id-inspect-lens-id", "71", "lens"],
            "/api/ee/transforms/71/inspect/lens",
        ),
        (["get-api-ee-transforms-python-library-path", "module.py"], "/api/ee/transforms-python/library/module.py"),
        (["get-api-ee-upload-management-tables"], "/api/ee/upload-management/tables"),
        (["list-channels"], "/api/channel"),
        (["get-comment"], "/api/comment"),
        (["list-cards"], "/api/card"),
        (["list-dashboards"], "/api/dashboard"),
        (["list-users"], "/api/user"),
        (["list-collections"], "/api/collection"),
        (["list-tables"], "/api/table"),
        (["get-database", "12"], "/api/database/12"),
        (["get-card", "13"], "/api/card/13"),
        (["list-embeddable-cards"], "/api/card/embeddable"),
        (["list-public-cards"], "/api/card/public"),
        (["get-card-param-search", "13", "abc", "Orange"], "/api/card/13/params/abc/search/Orange"),
        (["get-card-param-values", "13", "abc"], "/api/card/13/params/abc/values"),
        (["get-card-dashboards", "13"], "/api/card/13/dashboards"),
        (["get-card-param-remapping", "13", "abc"], "/api/card/13/params/abc/remapping"),
        (["get-card-query-metadata", "13"], "/api/card/13/query_metadata"),
        (["get-card-series", "13"], "/api/card/13/series"),
        (["get-dashboard", "14"], "/api/dashboard/14"),
        (
            ["get-dashboard-params-valid-filter-fields", "--filtered", "11", "--filtering", "22"],
            "/api/dashboard/params/valid-filter-fields",
        ),
        (["get-dashboard-dashcard-execute", "14", "22"], "/api/dashboard/14/dashcard/22/execute"),
        (["get-dashboard-embeddable"], "/api/dashboard/embeddable"),
        (["get-dashboard-public"], "/api/dashboard/public"),
        (["get-dashboard-items", "14"], "/api/dashboard/14/items"),
        (["get-dashboard-param-remapping", "14", "abc"], "/api/dashboard/14/params/abc/remapping"),
        (["get-dashboard-param-search", "14", "abc", "Orange"], "/api/dashboard/14/params/abc/search/Orange"),
        (["get-dashboard-param-values", "14", "abc"], "/api/dashboard/14/params/abc/values"),
        (["get-dashboard-query-metadata", "14"], "/api/dashboard/14/query_metadata"),
        (["get-dashboard-related", "14"], "/api/dashboard/14/related"),
        (["get-user", "15"], "/api/user/15"),
        (["list-user-recipients"], "/api/user/recipients"),
        (["get-user-key-value-namespace", "user"], "/api/user-key-value/namespace/user"),
        (["get-user-key-value-namespace-key", "user", "foo"], "/api/user-key-value/namespace/user/key/foo"),
        (["get-collection", "7"], "/api/collection/7"),
        (["get-collection", "root"], "/api/collection/root"),
        (["get-collection-dashboard-question-candidates", "7"], "/api/collection/7/dashboard-question-candidates"),
        (["get-collection-items", "7"], "/api/collection/7/items"),
        (["get-collection-root"], "/api/collection/root"),
        (["get-collection-root-dashboard-question-candidates"], "/api/collection/root/dashboard-question-candidates"),
        (["get-collection-root-items"], "/api/collection/root/items"),
        (["get-collection-trash"], "/api/collection/trash"),
        (["get-collection-tree"], "/api/collection/tree"),
        (["get-collection-graph"], "/api/collection/graph"),
        (["get-card-table-fks", "16"], "/api/table/card__16/fks"),
        (["get-card-table-query-metadata", "16"], "/api/table/card__16/query_metadata"),
        (["get-table", "16"], "/api/table/16"),
        (["get-table-fks", "16"], "/api/table/16/fks"),
        (["get-table-query-metadata", "16"], "/api/table/16/query_metadata"),
        (["get-table-related", "16"], "/api/table/16/related"),
        (["get-table-data", "16"], "/api/table/16/data"),
        (["get-field", "17"], "/api/field/17"),
        (["get-field-related", "17"], "/api/field/17/related"),
        (["get-field-remapping", "17", "18"], "/api/field/17/remapping/18"),
        (["search-field-values", "17", "abc"], "/api/field/17/search/abc"),
        (["get-field-summary", "17"], "/api/field/17/summary"),
        (["get-field-values", "17"], "/api/field/17/values"),
        (["get-embed-card", "tok"], "/api/embed/card/tok"),
        (["get-embed-card-param-remapping", "tok", "p"], "/api/embed/card/tok/params/p/remapping"),
        (["get-embed-card-param-search", "tok", "p", "pre"], "/api/embed/card/tok/params/p/search/pre"),
        (["get-embed-card-param-values", "tok", "p"], "/api/embed/card/tok/params/p/values"),
        (["get-embed-card-query", "tok"], "/api/embed/card/tok/query"),
        (["export-embed-card-query", "tok", "csv"], "/api/embed/card/tok/query/csv"),
        (["get-embed-dashboard", "tok"], "/api/embed/dashboard/tok"),
        (["get-embed-dashboard-card", "tok", "11", "12"], "/api/embed/dashboard/tok/dashcard/11/card/12"),
        (["export-embed-dashboard-card", "tok", "11", "12", "csv"], "/api/embed/dashboard/tok/dashcard/11/card/12/csv"),
        (["get-embed-dashboard-param-remapping", "tok", "p"], "/api/embed/dashboard/tok/params/p/remapping"),
        (["get-embed-dashboard-param-search", "tok", "p", "pre"], "/api/embed/dashboard/tok/params/p/search/pre"),
        (["get-embed-dashboard-param-values", "tok", "p"], "/api/embed/dashboard/tok/params/p/values"),
        (["get-embed-pivot-card-query", "tok"], "/api/embed/pivot/card/tok/query"),
        (["get-embed-pivot-dashboard-card", "tok", "11", "12"], "/api/embed/pivot/dashboard/tok/dashcard/11/card/12"),
        (["get-embed-card-tile", "tok", "1", "2", "3"], "/api/embed/tiles/card/tok/1/2/3"),
        (
            ["get-embed-dashboard-card-tile", "tok", "11", "12", "1", "2", "3"],
            "/api/embed/tiles/dashboard/tok/dashcard/11/card/12/1/2/3",
        ),
        (["list-embed-themes"], "/api/embed-theme"),
        (["get-embed-theme", "theme"], "/api/embed-theme/theme"),
        (["get-public-action", "uuid"], "/api/public/action/uuid"),
        (["get-public-card", "uuid"], "/api/public/card/uuid"),
        (["get-public-card-param-remapping", "uuid", "p"], "/api/public/card/uuid/params/p/remapping"),
        (["get-public-card-param-search", "uuid", "p", "q"], "/api/public/card/uuid/params/p/search/q"),
        (["get-public-card-param-values", "uuid", "p"], "/api/public/card/uuid/params/p/values"),
        (["get-public-card-query", "uuid"], "/api/public/card/uuid/query"),
        (["get-public-card-query-export", "uuid", "csv"], "/api/public/card/uuid/query/csv"),
        (["get-public-dashboard", "uuid"], "/api/public/dashboard/uuid"),
        (["get-public-dashboard-card", "uuid", "11", "12"], "/api/public/dashboard/uuid/dashcard/11/card/12"),
        (["get-public-dashboard-dashcard-execute", "uuid", "11"], "/api/public/dashboard/uuid/dashcard/11/execute"),
        (["get-public-dashboard-param-remapping", "uuid", "p"], "/api/public/dashboard/uuid/params/p/remapping"),
        (["get-public-dashboard-param-search", "uuid", "p", "q"], "/api/public/dashboard/uuid/params/p/search/q"),
        (["get-public-dashboard-param-values", "uuid", "p"], "/api/public/dashboard/uuid/params/p/values"),
        (["get-public-document", "uuid"], "/api/public/document/uuid"),
        (["get-public-document-card", "uuid", "12"], "/api/public/document/uuid/card/12"),
        (["get-public-oembed"], "/api/public/oembed"),
        (["get-public-pivot-card-query", "uuid"], "/api/public/pivot/card/uuid/query"),
        (
            ["get-public-pivot-dashboard-card", "uuid", "11", "12"],
            "/api/public/pivot/dashboard/uuid/dashcard/11/card/12",
        ),
        (["get-public-card-tile", "uuid", "1", "2", "3"], "/api/public/tiles/card/uuid/1/2/3"),
        (
            ["get-public-dashboard-card-tile", "uuid", "11", "12", "1", "2", "3"],
            "/api/public/tiles/dashboard/uuid/dashcard/11/card/12/1/2/3",
        ),
        (["list-pulses"], "/api/pulse"),
        (["get-pulse-form-input"], "/api/pulse/form_input"),
        (["get-pulse", "31"], "/api/pulse/31"),
        (["get-revisions", "card", "13"], "/api/revision"),
        (["get-entity-revisions", "card", "13"], "/api/revision/card/13"),
        (["search", "--q", "orders"], "/api/search"),
        (["get-search-weights"], "/api/search/weights"),
        (["get-preview-embed-card", "tok"], "/api/preview_embed/card/tok"),
        (
            ["get-preview-embed-card-param-remapping", "tok", "p"],
            "/api/preview_embed/card/tok/params/p/remapping",
        ),
        (["get-preview-embed-card-param-values", "tok", "p"], "/api/preview_embed/card/tok/params/p/values"),
        (["get-preview-embed-card-query", "tok"], "/api/preview_embed/card/tok/query"),
        (["get-preview-embed-dashboard", "tok"], "/api/preview_embed/dashboard/tok"),
        (
            ["get-preview-embed-dashboard-card", "tok", "11", "12"],
            "/api/preview_embed/dashboard/tok/dashcard/11/card/12",
        ),
        (
            ["get-preview-embed-dashboard-param-remapping", "tok", "p"],
            "/api/preview_embed/dashboard/tok/params/p/remapping",
        ),
        (
            ["get-preview-embed-dashboard-param-search", "tok", "p", "q"],
            "/api/preview_embed/dashboard/tok/params/p/search/q",
        ),
        (
            ["get-preview-embed-dashboard-param-values", "tok", "p"],
            "/api/preview_embed/dashboard/tok/params/p/values",
        ),
        (["get-preview-embed-pivot-card-query", "tok"], "/api/preview_embed/pivot/card/tok/query"),
        (
            ["get-preview-embed-pivot-dashboard-card", "tok", "11", "12"],
            "/api/preview_embed/pivot/dashboard/tok/dashcard/11/card/12",
        ),
        (["get-preview-embed-card-tile", "tok", "1", "2", "3"], "/api/preview_embed/tiles/card/tok/1/2/3"),
        (
            ["get-preview-embed-dashboard-card-tile", "tok", "11", "12", "1", "2", "3"],
            "/api/preview_embed/tiles/dashboard/tok/dashcard/11/card/12/1/2/3",
        ),
        (["get-geojson", "--url", "https://example.test/map.json"], "/api/geojson"),
        (["get-geojson-key", "world"], "/api/geojson/world"),
        (["get-glossary"], "/api/glossary"),
        (["get-logger-logs"], "/api/logger/logs"),
        (["get-logger-presets"], "/api/logger/presets"),
        (["get-login-history-current"], "/api/login-history/current"),
        (["list-measures"], "/api/measure"),
        (["get-measure", "21"], "/api/measure/21"),
        (["get-measure-dimension-remapping", "21", "country"], "/api/measure/21/dimension/country/remapping"),
        (["search-measure-dimension-values", "21", "country"], "/api/measure/21/dimension/country/search"),
        (["get-measure-dimension-values", "21", "country"], "/api/measure/21/dimension/country/values"),
        (["list-metrics"], "/api/metric"),
        (["get-metric", "22"], "/api/metric/22"),
        (["get-metric-dimension-remapping", "22", "country"], "/api/metric/22/dimension/country/remapping"),
        (["search-metric-dimension-values", "22", "country"], "/api/metric/22/dimension/country/search"),
        (["get-metric-dimension-values", "22", "country"], "/api/metric/22/dimension/country/values"),
        (["get-api-mt-gtap"], "/api/mt/gtap"),
        (["get-api-mt-gtap-id", "12"], "/api/mt/gtap/12"),
        (["get-api-mt-user-attributes"], "/api/mt/user/attributes"),
        (["get-api-metabot-settings"], "/api/metabot/settings"),
        (["get-api-metabot-metabot"], "/api/metabot/metabot"),
        (["get-api-metabot-metabot-id", "7"], "/api/metabot/metabot/7"),
        (["get-api-metabot-metabot-id-prompt-suggestions", "7"], "/api/metabot/metabot/7/prompt-suggestions"),
        (["get-api-metabot-permissions-user-permissions"], "/api/metabot/permissions/user-permissions"),
        (["list-model-indexes"], "/api/model-index"),
        (["get-model-index", "17"], "/api/model-index/17"),
        (["list-native-query-snippets"], "/api/native-query-snippet"),
        (["get-native-query-snippet", "18"], "/api/native-query-snippet/18"),
        (["list-notifications"], "/api/notification"),
        (["get-notification", "41"], "/api/notification/41"),
        (["list-persisted-info"], "/api/persist"),
        (["get-persisted-info-by-card", "13"], "/api/persist/card/13"),
        (["get-persisted-info", "99"], "/api/persist/99"),
        (["get-api-premium-features-token-status"], "/api/premium-features/token/status"),
        (["get-api-slack-app-info"], "/api/slack/app-info"),
        (["get-api-slack-manifest"], "/api/slack/manifest"),
        (["get-permissions-graph"], "/api/permissions/graph"),
        (["get-permissions-graph-db", "12"], "/api/permissions/graph/db/12"),
        (["get-permissions-graph-group", "4"], "/api/permissions/graph/group/4"),
        (["list-permissions-groups"], "/api/permissions/group"),
        (["get-permissions-group", "4"], "/api/permissions/group/4"),
        (["get-permissions-membership"], "/api/permissions/membership"),
        (["list-segments"], "/api/segment"),
        (["get-segment", "23"], "/api/segment/23"),
        (["get-segment-related", "23"], "/api/segment/23/related"),
        (["validate-password-reset-token", "tok"], "/api/session/password_reset_token_valid"),
        (["get-session-properties"], "/api/session/properties"),
        (["list-settings"], "/api/setting"),
        (["get-setting", "site-name"], "/api/setting/site-name"),
        (["get-task"], "/api/task"),
        (["get-task-info"], "/api/task/info"),
        (["get-task-runs"], "/api/task/runs"),
        (
            ["get-task-runs-entities", "--run-type", "sync", "--started-at", "2026-01-01"],
            "/api/task/runs/entities",
        ),
        (["get-task-runs-id", "44"], "/api/task/runs/44"),
        (["get-task-unique-tasks"], "/api/task/unique-tasks"),
        (["get-task-id", "45"], "/api/task/45"),
        (["get-tiles-card", "13", "1", "2", "3", "--lat-field", "lat", "--lon-field", "lon"], "/api/tiles/13/1/2/3"),
        (
            [
                "get-tiles-dashboard-card",
                "14",
                "22",
                "13",
                "1",
                "2",
                "3",
                "--lat-field",
                "lat",
                "--lon-field",
                "lon",
            ],
            "/api/tiles/14/dashcard/22/card/13/1/2/3",
        ),
        (
            ["get-tiles-query", "1", "2", "3", "--query", "{}", "--lat-field", "lat", "--lon-field", "lon"],
            "/api/tiles/1/2/3",
        ),
        (["list-timelines"], "/api/timeline"),
        (["get-timeline-collection-root"], "/api/timeline/collection/root"),
        (["get-timeline-collection", "root"], "/api/timeline/collection/root"),
        (["get-timeline", "51"], "/api/timeline/51"),
        (["get-timeline-event", "61"], "/api/timeline-event/61"),
        (["get-api-transform"], "/api/transform"),
        (["get-api-transform-run"], "/api/transform/run"),
        (["get-api-transform-run-run-id", "81"], "/api/transform/run/81"),
        (["get-api-transform-id", "71"], "/api/transform/71"),
        (["get-api-transform-id-dependencies", "71"], "/api/transform/71/dependencies"),
        (["get-api-transform-job"], "/api/transform-job"),
        (["get-api-transform-job-job-id", "91"], "/api/transform-job/91"),
        (["get-api-transform-job-job-id-transforms", "91"], "/api/transform-job/91/transforms"),
        (["get-api-transform-tag"], "/api/transform-tag"),
        (["get-api-llm-list-models"], "/api/llm/list-models"),
        (["get-random-token"], "/api/util/random_token"),
    ],
)
def test_read_endpoint_commands_cover_handwritten_surface(
    monkeypatch: pytest.MonkeyPatch,
    command: list[str],
    expected_path: str,
) -> None:
    monkeypatch.setattr(cli.runtime, "create_client", lambda _settings: _ClientWithRequestMethods())

    result = runner.invoke(
        cli.app,
        ["--base-url", "http://localhost:3000", "--api-key", "abc", *command],
    )

    assert result.exit_code == 0
    _assert_json_contains(result.stdout, {"method": "GET", "path": expected_path})


@pytest.mark.parametrize(
    ("command", "expected_method", "expected_path"),
    [
        (["create-action", '{"name":"action"}'], "POST", "/api/action"),
        (["create-channel", '{"name":"Slack"}'], "POST", "/api/channel"),
        (["test-channel", '{"name":"Slack"}'], "POST", "/api/channel/test"),
        (["create-comment", '{"text":"Hi","model":"card","model_id":13}'], "POST", "/api/comment"),
        (["get-comment-mentions"], "GET", "/api/comment/mentions"),
        (["update-comment", "11", '{"text":"updated"}'], "PUT", "/api/comment/11"),
        (["post-comment-reaction", "11", '{"emoji":"👍"}'], "POST", "/api/comment/11/reaction"),
        (["get-channel", "11"], "GET", "/api/channel/11"),
        (["update-channel", "11", '{"name":"Slack"}'], "PUT", "/api/channel/11"),
        (["create-cloud-migration", '{"environment":"prod"}'], "POST", "/api/cloud-migration"),
        (["cancel-cloud-migration"], "PUT", "/api/cloud-migration/cancel"),
        (["create-collection", '{"name":"New"}'], "POST", "/api/collection"),
        (["create-dashboard", '{"name":"Sales"}'], "POST", "/api/dashboard"),
        (["query-dashboard-card", "14", "22", "33", '{"x":1}'], "POST", "/api/dashboard/14/dashcard/22/card/33/query"),
        (
            ["query-dashboard-card-export", "14", "22", "33", "xlsx", '{"x":1}'],
            "POST",
            "/api/dashboard/14/dashcard/22/card/33/query/xlsx",
        ),
        (
            ["query-dashboard-card-pivot", "14", "22", "33", '{"x":1}'],
            "POST",
            "/api/dashboard/pivot/14/dashcard/22/card/33/query",
        ),
        (["save-dashboard", '{"name":"Sales"}'], "POST", "/api/dashboard/save"),
        (["save-dashboard-to-collection", "root", '{"name":"Sales"}'], "POST", "/api/dashboard/save/collection/root"),
        (
            ["execute-dashboard-dashcard", "14", "22", "--parameters", '{"id":1}'],
            "POST",
            "/api/dashboard/14/dashcard/22/execute",
        ),
        (["create-dashboard-public-link", "14"], "POST", "/api/dashboard/14/public_link"),
        (["delete-dashboard-public-link", "14"], "DELETE", "/api/dashboard/14/public_link"),
        (["copy-dashboard", "14"], "POST", "/api/dashboard/14/copy"),
        (["delete-dashboard", "14"], "DELETE", "/api/dashboard/14"),
        (["update-dashboard", "14", '{"name":"Sales"}'], "PUT", "/api/dashboard/14"),
        (["update-dashboard-cards", "14", '{"cards":[]}'], "PUT", "/api/dashboard/14/cards"),
        (["get-collection-graph"], "GET", "/api/collection/graph"),
        (["put-collection-graph", '{"groups":["admin"]}'], "PUT", "/api/collection/graph"),
        (
            ["post-collection-root-move-dashboard-question-candidates", '{"card_ids":[1]}'],
            "POST",
            "/api/collection/root/move-dashboard-question-candidates",
        ),
        (
            ["post-collection-move-dashboard-question-candidates", "7", '{"card_ids":[1]}'],
            "POST",
            "/api/collection/7/move-dashboard-question-candidates",
        ),
        (["update-collection", "7", '{"name":"New"}'], "PUT", "/api/collection/7"),
        (["get-comment"], "GET", "/api/comment"),
        (["delete-comment", "7"], "DELETE", "/api/comment/7"),
        (["delete-collection", "7"], "DELETE", "/api/collection/7"),
        (["delete-action", "11"], "DELETE", "/api/action/11"),
        (["card-collections", "1,2", "--collection-id", "root"], "POST", "/api/card/collections"),
        (["cards-dashboards", "1,2"], "POST", "/api/cards/dashboards"),
        (["list-embeddable-cards"], "GET", "/api/card/embeddable"),
        (["pivot-query", "13", '{"x":1}'], "POST", "/api/card/pivot/13/query"),
        (["list-public-cards"], "GET", "/api/card/public"),
        (["create-card-public-link", "13"], "POST", "/api/card/13/public_link"),
        (["delete-card-public-link", "13"], "DELETE", "/api/card/13/public_link"),
        (["query-card", "13", '{"x":1}'], "POST", "/api/card/13/query"),
        (["query-card-export", "13", "csv", '{"x":1}'], "POST", "/api/card/13/query/csv"),
        (["move-cards", '{"card_ids":[1],"collection_id":"root"}'], "POST", "/api/cards/move"),
        (["update-card", "13", '{"name":"copy"}'], "PUT", "/api/card/13"),
        (["delete-card", "13"], "DELETE", "/api/card/13"),
        (["copy-card", "13"], "POST", "/api/card/13/copy"),
        (["get-card-dashboards", "13"], "GET", "/api/card/13/dashboards"),
        (["get-card-param-remapping", "13", "abc"], "GET", "/api/card/13/params/abc/remapping"),
        (["get-card-query-metadata", "13"], "GET", "/api/card/13/query_metadata"),
        (["get-card-series", "13"], "GET", "/api/card/13/series"),
        (["update-action", "11", '{"name":"action"}'], "PUT", "/api/action/11"),
        (["execute-action", "11", "--parameters", '{"id":1}'], "POST", "/api/action/11/execute"),
        (["create-action-public-link", "11"], "POST", "/api/action/11/public_link"),
        (["delete-action-public-link", "11"], "DELETE", "/api/action/11/public_link"),
        (["update-bookmark-ordering", '{"ids":[1]}'], "PUT", "/api/bookmark/ordering"),
        (
            ["get-cache", "--limit", "10", "--offset", "20", "--sort-column", "name", "--sort-direction", "asc"],
            "GET",
            "/api/cache",
        ),
        (["put-cache", '{"type":"lru"}'], "PUT", "/api/cache"),
        (["delete-cache"], "DELETE", "/api/cache"),
        (["invalidate-cache", '{"dashboard":[15],"include":["question"]}'], "POST", "/api/cache/invalidate"),
        (["create-bookmark", "card", "1"], "POST", "/api/bookmark/card/1"),
        (["delete-bookmark", "card", "1"], "DELETE", "/api/bookmark/card/1"),
        (["create-api-key", '{"name":"key","group_id":1}'], "POST", "/api/api-key"),
        (["update-api-key", "7", '{"name":"key"}'], "PUT", "/api/api-key/7"),
        (["delete-api-key", "7"], "DELETE", "/api/api-key/7"),
        (["regenerate-api-key", "7"], "PUT", "/api/api-key/7/regenerate"),
        (["analyze-chart", '{"image":"base64"}'], "POST", "/api/ai-entity-analysis/analyze-chart"),
        (["delete-alert-subscription", "7"], "DELETE", "/api/alert/7/subscription"),
        (["create-analytics-event-batch", '{"events":[]}'], "POST", "/api/analytics/internal"),
        (["agent-execute", '{"query":"abc"}'], "POST", "/api/agent/v1/execute"),
        (["agent-search", '{"query":"orders"}'], "POST", "/api/agent/v1/search"),
        (["agent-construct-query", '{"source":"x"}'], "POST", "/api/agent/v2/construct-query"),
        (["agent-query", '{"source":"x"}'], "POST", "/api/agent/v2/query"),
        (["create-recent", '{"model":"card","model_id":1}'], "POST", "/api/activity/recents"),
        (
            ["data-studio-table-discard-values", '{"table_ids":[1]}'],
            "POST",
            "/api/data-studio/table/discard-values",
        ),
        (["data-studio-table-edit", '{"table_ids":[1]}'], "POST", "/api/data-studio/table/edit"),
        (
            ["data-studio-table-rescan-values", '{"table_ids":[1]}'],
            "POST",
            "/api/data-studio/table/rescan-values",
        ),
        (["data-studio-table-selection", '{"table_ids":[1]}'], "POST", "/api/data-studio/table/selection"),
        (["data-studio-table-sync-schema", '{"table_ids":[1]}'], "POST", "/api/data-studio/table/sync-schema"),
        (["create-sample-database"], "POST", "/api/database/sample_database"),
        (["delete-database", "12"], "DELETE", "/api/database/12"),
        (["discard-database-values", "12"], "POST", "/api/database/12/discard_values"),
        (["dismiss-database-spinner", "12"], "POST", "/api/database/12/dismiss_spinner"),
        (["import-database-metadata", '{"databases":[]}'], "POST", "/api/database/metadata"),
        (["rescan-database-values", "12"], "POST", "/api/database/12/rescan_values"),
        (["sync-database-schema", "12"], "POST", "/api/database/12/sync_schema"),
        (["update-database", "12", '{"name":"analytics"}'], "PUT", "/api/database/12"),
        (["validate-database", '{"engine":"postgres","details":{}}'], "POST", "/api/database/validate"),
        (["post-dataset", "{}"], "POST", "/api/dataset"),
        (["post-dataset-native", "{}"], "POST", "/api/dataset/native"),
        (["post-dataset-parameter-remapping", "{}"], "POST", "/api/dataset/parameter/remapping"),
        (["post-dataset-parameter-search", "Orange", "{}"], "POST", "/api/dataset/parameter/search/Orange"),
        (["post-dataset-parameter-values", "{}"], "POST", "/api/dataset/parameter/values"),
        (["post-dataset-pivot", "{}"], "POST", "/api/dataset/pivot"),
        (["post-dataset-query-metadata", "{}"], "POST", "/api/dataset/query_metadata"),
        (["post-dataset-export", "csv", "{}"], "POST", "/api/dataset/csv"),
        (["create-document", '{"name":"Spec"}'], "POST", "/api/document"),
        (["update-document", "12", '{"name":"Spec"}'], "PUT", "/api/document/12"),
        (["delete-document", "12"], "DELETE", "/api/document/12"),
        (
            ["export-document-card-query", "12", "13", "csv", "{}"],
            "POST",
            "/api/document/12/card/13/query/csv",
        ),
        (["create-document-public-link", "12"], "POST", "/api/document/12/public-link"),
        (["delete-document-public-link", "12"], "DELETE", "/api/document/12/public-link"),
        (["copy-document", "12", '{"name":"Copy"}'], "POST", "/api/document/12/copy"),
        (["ee-action-v2-execute", "{}"], "POST", "/api/ee/action-v2/execute"),
        (["ee-action-v2-execute-bulk", "{}"], "POST", "/api/ee/action-v2/execute-bulk"),
        (["ee-action-v2-execute-form", "{}"], "POST", "/api/ee/action-v2/execute-form"),
        (
            ["put-ee-advanced-permissions-application-graph", "{}"],
            "PUT",
            "/api/ee/advanced-permissions/application/graph",
        ),
        (
            ["delete-ee-advanced-permissions-impersonation", "9"],
            "DELETE",
            "/api/ee/advanced-permissions/impersonation/9",
        ),
        (["put-ee-ai-controls-permissions", "{}"], "PUT", "/api/ee/ai-controls/permissions"),
        (["enable-ee-ai-controls-permissions-advanced"], "POST", "/api/ee/ai-controls/permissions/advanced"),
        (["disable-ee-ai-controls-permissions-advanced"], "DELETE", "/api/ee/ai-controls/permissions/advanced"),
        (["put-ee-ai-controls-usage-instance", "{}"], "PUT", "/api/ee/ai-controls/usage/instance"),
        (["put-ee-ai-controls-usage-tenant-id", "tenant", "{}"], "PUT", "/api/ee/ai-controls/usage/tenant/tenant"),
        (["put-ee-ai-controls-usage-group-id", "4", "{}"], "PUT", "/api/ee/ai-controls/usage/group/4"),
        (["post-ee-audit-app-analytics-dev-export"], "POST", "/api/ee/audit-app/analytics-dev/export"),
        (["delete-ee-audit-app-user-id-subscriptions", "15"], "DELETE", "/api/ee/audit-app/user/15/subscriptions"),
        (["post-ee-cloud-add-ons-product-type", "pro", "{}"], "POST", "/api/ee/cloud-add-ons/pro"),
        (["delete-ee-cloud-add-ons-product-type", "pro"], "DELETE", "/api/ee/cloud-add-ons/pro"),
        (["post-ee-cloud-proxy-operation-id", "op", "{}"], "POST", "/api/ee/cloud-proxy/op"),
        (
            ["post-ee-content-translation-upload-dictionary", "{}"],
            "POST",
            "/api/ee/content-translation/upload-dictionary",
        ),
        (["post-ee-data-studio-table-publish-tables", "{}"], "POST", "/api/ee/data-studio/table/publish-tables"),
        (["post-ee-data-studio-table-unpublish-tables", "{}"], "POST", "/api/ee/data-studio/table/unpublish-tables"),
        (
            ["post-ee-database-replication-connection-database-id", "12", "{}"],
            "POST",
            "/api/ee/database-replication/connection/12",
        ),
        (
            ["delete-ee-database-replication-connection-database-id", "12"],
            "DELETE",
            "/api/ee/database-replication/connection/12",
        ),
        (
            ["post-ee-database-replication-connection-database-id-preview", "12", "{}"],
            "POST",
            "/api/ee/database-replication/connection/12/preview",
        ),
        (
            ["post-ee-database-routing-destination-database", "{}"],
            "POST",
            "/api/ee/database-routing/destination-database",
        ),
        (
            ["put-ee-database-routing-router-database-id", "12", "{}"],
            "PUT",
            "/api/ee/database-routing/router-database/12",
        ),
        (["post-api-ee-dependencies-check-card", "{}"], "POST", "/api/ee/dependencies/check-card"),
        (["post-api-ee-dependencies-check-snippet", "{}"], "POST", "/api/ee/dependencies/check-snippet"),
        (["post-api-ee-dependencies-check-transform", "{}"], "POST", "/api/ee/dependencies/check-transform"),
        (["put-api-ee-email-override", "{}"], "PUT", "/api/ee/email/override"),
        (["delete-api-ee-email-override"], "DELETE", "/api/ee/email/override"),
        (["post-api-ee-gsheets-connection", "{}"], "POST", "/api/ee/gsheets/connection"),
        (["delete-api-ee-gsheets-connection"], "DELETE", "/api/ee/gsheets/connection"),
        (["post-api-ee-gsheets-connection-sync"], "POST", "/api/ee/gsheets/connection/sync"),
        (["post-api-ee-library"], "POST", "/api/ee/library"),
        (["post-api-ee-remote-sync-create-branch"], "POST", "/api/ee/remote-sync/create-branch"),
        (["post-api-ee-remote-sync-current-task-cancel"], "POST", "/api/ee/remote-sync/current-task/cancel"),
        (["post-api-ee-remote-sync-export"], "POST", "/api/ee/remote-sync/export"),
        (["post-api-ee-remote-sync-import"], "POST", "/api/ee/remote-sync/import"),
        (["put-api-ee-remote-sync-settings", "{}"], "PUT", "/api/ee/remote-sync/settings"),
        (["post-api-ee-remote-sync-stash"], "POST", "/api/ee/remote-sync/stash"),
        (
            ["post-api-ee-replacement-check-replace-source", "{}"],
            "POST",
            "/api/ee/replacement/check-replace-source",
        ),
        (
            ["post-api-ee-replacement-replace-model-with-transform", "{}"],
            "POST",
            "/api/ee/replacement/replace-model-with-transform",
        ),
        (["post-api-ee-replacement-replace-source", "{}"], "POST", "/api/ee/replacement/replace-source"),
        (["post-api-ee-replacement-runs-id-cancel", "run"], "POST", "/api/ee/replacement/runs/run/cancel"),
        (["post-ee-scim-api-key"], "POST", "/api/ee/scim/api_key"),
        (["post-ee-scim-v2-groups", "{}"], "POST", "/api/ee/scim/v2/Groups"),
        (["put-ee-scim-v2-groups-id", "group", "{}"], "PUT", "/api/ee/scim/v2/Groups/group"),
        (["delete-ee-scim-v2-groups-id", "group"], "DELETE", "/api/ee/scim/v2/Groups/group"),
        (["post-ee-scim-v2-users", "{}"], "POST", "/api/ee/scim/v2/Users"),
        (["put-ee-scim-v2-users-id", "user", "{}"], "PUT", "/api/ee/scim/v2/Users/user"),
        (["patch-ee-scim-v2-users-id", "user", "{}"], "PATCH", "/api/ee/scim/v2/Users/user"),
        (["post-ee-security-center-acknowledge", "{}"], "POST", "/api/ee/security-center/acknowledge"),
        (["post-ee-security-center-sync"], "POST", "/api/ee/security-center/sync"),
        (["post-ee-security-center-test-notification"], "POST", "/api/ee/security-center/test-notification"),
        (
            ["post-ee-security-center-advisory-id-acknowledge", "advisory"],
            "POST",
            "/api/ee/security-center/advisory/acknowledge",
        ),
        (["post-api-ee-serialization-export"], "POST", "/api/ee/serialization/export"),
        (
            ["post-api-ee-serialization-import", "--file", "archive.tar.gz"],
            "POST",
            "/api/ee/serialization/import",
        ),
        (["post-api-ee-support-access-grant", "{}"], "POST", "/api/ee/support-access-grant"),
        (["put-api-ee-support-access-grant-id-revoke", "grant"], "PUT", "/api/ee/support-access-grant/grant/revoke"),
        (["post-api-ee-tenant", "{}"], "POST", "/api/ee/tenant"),
        (["put-api-ee-tenant-id", "tenant", "{}"], "PUT", "/api/ee/tenant/tenant"),
        (
            ["post-api-ee-transforms-id-inspect-lens-id-query", "71", "lens", "{}"],
            "POST",
            "/api/ee/transforms/71/inspect/lens/query",
        ),
        (
            ["put-api-ee-transforms-python-library-path", "module.py", "{}"],
            "PUT",
            "/api/ee/transforms-python/library/module.py",
        ),
        (["post-api-ee-transforms-python-test-run", "{}"], "POST", "/api/ee/transforms-python/test-run"),
        (["delete-api-ee-upload-management-tables-id", "16"], "DELETE", "/api/ee/upload-management/tables/16"),
        (["update-email-settings", '{"host":"smtp.local"}'], "PUT", "/api/email"),
        (["delete-email-settings"], "DELETE", "/api/email"),
        (["test-email", '{"to":"user@example.com"}'], "POST", "/api/email/test"),
        (["create-embed-theme", '{"name":"Light"}'], "POST", "/api/embed-theme"),
        (["seed-default-embed-themes", "{}"], "POST", "/api/embed-theme/seed-defaults"),
        (["update-embed-theme", "theme", '{"name":"Light"}'], "PUT", "/api/embed-theme/theme"),
        (["delete-embed-theme", "theme"], "DELETE", "/api/embed-theme/theme"),
        (["copy-embed-theme", "theme"], "POST", "/api/embed-theme/theme/copy"),
        (["create-glossary-entry", '{"term":"Revenue"}'], "POST", "/api/glossary"),
        (["update-glossary-entry", "5", '{"term":"Revenue"}'], "PUT", "/api/glossary/5"),
        (["delete-glossary-entry", "5"], "DELETE", "/api/glossary/5"),
        (["create-logger-adjustment", '{"level":"debug"}'], "POST", "/api/logger/adjustment"),
        (["delete-logger-adjustment"], "DELETE", "/api/logger/adjustment"),
        (["create-measure", '{"name":"Total"}'], "POST", "/api/measure"),
        (["update-measure", "21", '{"name":"Total"}'], "PUT", "/api/measure/21"),
        (["post-metric-breakout-values", "{}"], "POST", "/api/metric/breakout-values"),
        (["post-metric-dataset", "{}"], "POST", "/api/metric/dataset"),
        (["post-api-mt-gtap", "{}"], "POST", "/api/mt/gtap"),
        (["post-api-mt-gtap-validate", "{}"], "POST", "/api/mt/gtap/validate"),
        (["put-api-mt-gtap-id", "12", "{}"], "PUT", "/api/mt/gtap/12"),
        (["delete-api-mt-gtap-id", "12"], "DELETE", "/api/mt/gtap/12"),
        (["put-api-mt-user-id-attributes", "15", "{}"], "PUT", "/api/mt/user/15/attributes"),
        (["put-permissions-graph", "{}"], "PUT", "/api/permissions/graph"),
        (["create-permissions-group", '{"name":"Analysts"}'], "POST", "/api/permissions/group"),
        (["update-permissions-group", "4", '{"name":"Analysts"}'], "PUT", "/api/permissions/group/4"),
        (["delete-permissions-group", "4"], "DELETE", "/api/permissions/group/4"),
        (["create-permissions-membership", '{"user_id":2,"group_id":4}'], "POST", "/api/permissions/membership"),
        (["clear-permissions-membership", "4"], "PUT", "/api/permissions/membership/4/clear"),
        (
            ["update-permissions-membership", "8", '{"user_id":2,"group_id":4}'],
            "PUT",
            "/api/permissions/membership/8",
        ),
        (["delete-permissions-membership", "8"], "DELETE", "/api/permissions/membership/8"),
        (["execute-public-action", "uuid"], "POST", "/api/public/action/uuid/execute"),
        (
            ["export-public-dashboard-card", "uuid", "11", "12", "csv", "{}"],
            "POST",
            "/api/public/dashboard/uuid/dashcard/11/card/12/csv",
        ),
        (
            ["execute-public-dashboard-dashcard", "uuid", "11"],
            "POST",
            "/api/public/dashboard/uuid/dashcard/11/execute",
        ),
        (
            ["export-public-document-card", "uuid", "12", "csv", "{}"],
            "POST",
            "/api/public/document/uuid/card/12/csv",
        ),
        (["create-pulse", '{"name":"Pulse"}'], "POST", "/api/pulse"),
        (["test-pulse", '{"name":"Pulse"}'], "POST", "/api/pulse/test"),
        (["update-pulse", "31", '{"name":"Pulse"}'], "PUT", "/api/pulse/31"),
        (["delete-pulse-subscription", "31"], "DELETE", "/api/pulse/31/subscription"),
        (["unsubscribe-pulse", '{"email":"user@example.com"}'], "POST", "/api/pulse/unsubscribe"),
        (["undo-pulse-unsubscribe", '{"email":"user@example.com"}'], "POST", "/api/pulse/unsubscribe/undo"),
        (["revert-revision", "card", "13", "2"], "POST", "/api/revision/revert"),
        (["force-search-reindex"], "POST", "/api/search/force-reindex"),
        (["re-init-search"], "POST", "/api/search/re-init"),
        (["update-search-weights", "{}"], "PUT", "/api/search/weights"),
        (["post-api-metabot-agent-streaming", "{}"], "POST", "/api/metabot/agent-streaming"),
        (["post-api-metabot-feedback", "{}"], "POST", "/api/metabot/feedback"),
        (["put-api-metabot-settings", "{}"], "PUT", "/api/metabot/settings"),
        (["post-api-metabot-document-generate-content", "{}"], "POST", "/api/metabot/document/generate-content"),
        (["put-api-metabot-metabot-id", "7", "{}"], "PUT", "/api/metabot/metabot/7"),
        (
            ["delete-api-metabot-metabot-id-prompt-suggestions", "7"],
            "DELETE",
            "/api/metabot/metabot/7/prompt-suggestions",
        ),
        (
            ["post-api-metabot-metabot-id-prompt-suggestions-regenerate", "7"],
            "POST",
            "/api/metabot/metabot/7/prompt-suggestions/regenerate",
        ),
        (
            ["delete-api-metabot-metabot-id-prompt-suggestions-prompt-id", "7", "3"],
            "DELETE",
            "/api/metabot/metabot/7/prompt-suggestions/3",
        ),
        (["post-api-metabot-slack-events", "{}"], "POST", "/api/metabot/slack/events"),
        (["post-api-metabot-slack-interactive", "{}"], "POST", "/api/metabot/slack/interactive"),
        (["put-api-metabot-slack-settings", "{}"], "PUT", "/api/metabot/slack/settings"),
        (["create-model-index", '{"model_id":13}'], "POST", "/api/model-index"),
        (["delete-model-index", "17"], "DELETE", "/api/model-index/17"),
        (["create-native-query-snippet", '{"name":"Snippet"}'], "POST", "/api/native-query-snippet"),
        (["update-native-query-snippet", "18", '{"name":"Snippet"}'], "PUT", "/api/native-query-snippet/18"),
        (["create-notification", '{"name":"Notification"}'], "POST", "/api/notification"),
        (["send-unsaved-notification", '{"name":"Notification"}'], "POST", "/api/notification/send"),
        (["update-notification", "41", '{"name":"Notification"}'], "PUT", "/api/notification/41"),
        (["send-notification", "41"], "POST", "/api/notification/41/send"),
        (["unsubscribe-notification", "41"], "POST", "/api/notification/41/unsubscribe"),
        (
            ["unsubscribe-notification-by-hash", '{"email":"user@example.com"}'],
            "POST",
            "/api/notification/unsubscribe",
        ),
        (
            ["undo-notification-unsubscribe", '{"email":"user@example.com"}'],
            "POST",
            "/api/notification/unsubscribe/undo",
        ),
        (["notify-attached-datawarehouse", "{}"], "POST", "/api/notify/db/attached_datawarehouse"),
        (["notify-database", "12", "{}"], "POST", "/api/notify/db/12"),
        (["notify-database-new-table", "12", "{}"], "POST", "/api/notify/db/12/new-table"),
        (["persist-card", "13"], "POST", "/api/persist/card/13/persist"),
        (["refresh-persisted-card", "13"], "POST", "/api/persist/card/13/refresh"),
        (["unpersist-card", "13"], "POST", "/api/persist/card/13/unpersist"),
        (["enable-database-persistence", "12"], "POST", "/api/persist/database/12/persist"),
        (["disable-database-persistence", "12"], "POST", "/api/persist/database/12/unpersist"),
        (["disable-persistence"], "POST", "/api/persist/disable"),
        (["enable-persistence"], "POST", "/api/persist/enable"),
        (["set-persistence-refresh-schedule", '{"cron":"0 0 * * * ?"}'], "POST", "/api/persist/set-refresh-schedule"),
        (["post-api-eid-translation-translate", "{}"], "POST", "/api/eid-translation/translate"),
        (["post-api-frontend-errors", "{}"], "POST", "/api/frontend-errors"),
        (["put-api-google-settings", "{}"], "PUT", "/api/google/settings"),
        (["put-api-ldap-settings", "{}"], "PUT", "/api/ldap/settings"),
        (["post-api-llm-extract-tables", "{}"], "POST", "/api/llm/extract-tables"),
        (["post-api-llm-generate-sql", "{}"], "POST", "/api/llm/generate-sql"),
        (["post-api-moderation-review", "{}"], "POST", "/api/moderation-review"),
        (["post-api-premium-features-token-refresh"], "POST", "/api/premium-features/token/refresh"),
        (["post-api-product-feedback", "{}"], "POST", "/api/product-feedback"),
        (["post-api-setup", "{}"], "POST", "/api/setup"),
        (["post-api-slack-bug-report", "{}"], "POST", "/api/slack/bug-report"),
        (["put-api-slack-settings", "{}"], "PUT", "/api/slack/settings"),
        (["post-api-upload-csv", "--body", "{}"], "POST", "/api/upload/csv"),
        (["create-segment", '{"name":"VIP"}'], "POST", "/api/segment"),
        (["update-segment", "23", '{"name":"VIP"}'], "PUT", "/api/segment/23"),
        (["delete-segment", "23"], "DELETE", "/api/segment/23"),
        (["login", '{"username":"user@example.com","password":"secret"}'], "POST", "/api/session"),
        (["logout"], "DELETE", "/api/session"),
        (["forgot-password", '{"email":"user@example.com"}'], "POST", "/api/session/forgot_password"),
        (["google-auth", '{"token":"abc"}'], "POST", "/api/session/google_auth"),
        (["check-password", '{"password":"secret"}'], "POST", "/api/session/password-check"),
        (["reset-password", '{"token":"tok","password":"secret"}'], "POST", "/api/session/reset_password"),
        (["update-settings", '{"site-name":"Metabase"}'], "PUT", "/api/setting"),
        (["update-setting", "site-name", '{"value":"Metabase"}'], "PUT", "/api/setting/site-name"),
        (["create-timeline", '{"name":"Timeline"}'], "POST", "/api/timeline"),
        (["update-timeline", "51", '{"name":"Timeline"}'], "PUT", "/api/timeline/51"),
        (["delete-timeline", "51"], "DELETE", "/api/timeline/51"),
        (["create-timeline-event", '{"name":"Event"}'], "POST", "/api/timeline-event"),
        (["update-timeline-event", "61", '{"name":"Event"}'], "PUT", "/api/timeline-event/61"),
        (["delete-timeline-event", "61"], "DELETE", "/api/timeline-event/61"),
        (["post-api-transform", "{}"], "POST", "/api/transform"),
        (["put-api-transform-id", "71", "{}"], "PUT", "/api/transform/71"),
        (["delete-api-transform-id", "71"], "DELETE", "/api/transform/71"),
        (["post-api-transform-id-cancel", "71"], "POST", "/api/transform/71/cancel"),
        (["post-api-transform-id-reset-checkpoint", "71"], "POST", "/api/transform/71/reset-checkpoint"),
        (["post-api-transform-id-run", "71"], "POST", "/api/transform/71/run"),
        (["delete-api-transform-id-table", "71"], "DELETE", "/api/transform/71/table"),
        (["post-api-transform-job", "{}"], "POST", "/api/transform-job"),
        (["put-api-transform-job-job-id", "91", "{}"], "PUT", "/api/transform-job/91"),
        (["delete-api-transform-job-job-id", "91"], "DELETE", "/api/transform-job/91"),
        (["post-api-transform-job-job-id-run", "91"], "POST", "/api/transform-job/91/run"),
        (["post-api-transform-tag", "{}"], "POST", "/api/transform-tag"),
        (["put-api-transform-tag-tag-id", "19", "{}"], "PUT", "/api/transform-tag/19"),
        (["delete-api-transform-tag-tag-id", "19"], "DELETE", "/api/transform-tag/19"),
        (["create-user", '{"email":"user@example.com"}'], "POST", "/api/user"),
        (["update-user", "15", '{"first_name":"Ada"}'], "PUT", "/api/user/15"),
        (["delete-user", "15"], "DELETE", "/api/user/15"),
        (["update-user-modal", "15", "query-builder"], "PUT", "/api/user/15/modal/query-builder"),
        (["update-user-password", "15", '{"password":"secret"}'], "PUT", "/api/user/15/password"),
        (["create-user-password-reset-url", "15"], "POST", "/api/user/15/password-reset-url"),
        (["reactivate-user", "15"], "PUT", "/api/user/15/reactivate"),
        (
            ["put-user-key-value-namespace-key", "user", "foo", '{"value":"bar"}'],
            "PUT",
            "/api/user-key-value/namespace/user/key/foo",
        ),
        (
            ["delete-user-key-value-namespace-key", "user", "foo"],
            "DELETE",
            "/api/user-key-value/namespace/user/key/foo",
        ),
        (["update-tables", '{"ids":[16]}'], "PUT", "/api/table"),
        (["update-table", "16", '{"name":"Orders"}'], "PUT", "/api/table/16"),
        (["append-table-csv", "16", "{}"], "POST", "/api/table/16/append-csv"),
        (["discard-table-values", "16"], "POST", "/api/table/16/discard_values"),
        (["update-table-fields-order", "16", '{"field_order":[1]}'], "PUT", "/api/table/16/fields/order"),
        (["replace-table-csv", "16", "{}"], "POST", "/api/table/16/replace-csv"),
        (["rescan-table-values", "16"], "POST", "/api/table/16/rescan_values"),
        (["sync-table-schema", "16"], "POST", "/api/table/16/sync_schema"),
        (["update-field", "17", '{"name":"Quantity"}'], "PUT", "/api/field/17"),
        (["set-field-dimension", "17", '{"type":"external"}'], "POST", "/api/field/17/dimension"),
        (["delete-field-dimension", "17"], "DELETE", "/api/field/17/dimension"),
        (["discard-field-values", "17"], "POST", "/api/field/17/discard_values"),
        (["rescan-field-values", "17"], "POST", "/api/field/17/rescan_values"),
        (["update-field-values", "17", '{"values":["A"]}'], "POST", "/api/field/17/values"),
    ],
)
def test_action_mutation_commands_cover_handwritten_surface(
    monkeypatch: pytest.MonkeyPatch,
    command: list[str],
    expected_method: str,
    expected_path: str,
) -> None:
    monkeypatch.setattr(cli.runtime, "create_client", lambda _settings: _ClientWithRequestMethods())

    result = runner.invoke(cli.app, ["--base-url", "http://localhost:3000", "--api-key", "abc", *command])

    assert result.exit_code == 0
    _assert_json_contains(result.stdout, {"method": expected_method, "path": expected_path})


@pytest.mark.parametrize(
    ("command", "expected_body"),
    [
        (["card-collections", "1,abc", "--collection-id", "root"], {"card_ids": [1, "abc"], "collection_id": "root"}),
        (["cards-dashboards", "1,abc"], {"card_ids": [1, "abc"]}),
    ],
)
def test_card_id_csv_commands_coerce_numeric_ids(
    monkeypatch: pytest.MonkeyPatch,
    command: list[str],
    expected_body: dict[str, object],
) -> None:
    monkeypatch.setattr(cli.runtime, "create_client", lambda _settings: _ClientWithRequestMethods())

    result = runner.invoke(cli.app, ["--base-url", "http://localhost:3000", "--api-key", "abc", *command])

    assert result.exit_code == 0
    assert _LAST_CALL["body"] == expected_body


@pytest.mark.parametrize(
    "command",
    [
        ["pivot-query", "13"],
        ["query-card", "13"],
        ["query-card-export", "13", "csv"],
    ],
)
def test_card_query_commands_default_missing_body_to_empty_object(
    monkeypatch: pytest.MonkeyPatch,
    command: list[str],
) -> None:
    spy = _RunSpyClient()
    monkeypatch.setattr(cli.runtime, "create_client", lambda _settings: spy)

    result = runner.invoke(cli.app, ["--base-url", "http://localhost:3000", "--api-key", "abc", *command])

    assert result.exit_code == 0
    assert spy.request_model is not None
    assert spy.request_model.model_dump()["body"] == {}


@pytest.mark.parametrize(
    "command",
    [
        ["query-dashboard-card", "14", "22", "33"],
        ["query-dashboard-card-export", "14", "22", "33", "xlsx"],
        ["query-dashboard-card-pivot", "14", "22", "33"],
    ],
)
def test_dashboard_query_commands_default_missing_body_to_none(
    monkeypatch: pytest.MonkeyPatch,
    command: list[str],
) -> None:
    spy = _RunSpyClient()
    monkeypatch.setattr(cli.runtime, "create_client", lambda _settings: spy)

    result = runner.invoke(cli.app, ["--base-url", "http://localhost:3000", "--api-key", "abc", *command])

    assert result.exit_code == 0
    assert spy.request_model is not None
    assert spy.request_model.model_dump()["body"] is None


def test_dashboard_filter_field_options_coerce_numeric_ids(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    spy = _RunSpyClient()
    monkeypatch.setattr(cli.runtime, "create_client", lambda _settings: spy)

    result = runner.invoke(
        cli.app,
        [
            "--base-url",
            "http://localhost:3000",
            "--api-key",
            "abc",
            "get-dashboard-params-valid-filter-fields",
            "--filtered",
            "11",
            "--filtered",
            "abc",
            "--filtering",
            "22",
        ],
    )

    assert result.exit_code == 0
    assert spy.request_model is not None
    assert spy.request_model.model_dump() == {"filtered": [11, "abc"], "filtering": [22]}


def test_create_question_command_posts_card_json(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(cli.runtime, "create_client", lambda _settings: _ClientWithRequestMethods())

    result = runner.invoke(
        cli.app,
        [
            "--base-url",
            "http://localhost:3000",
            "--api-key",
            "abc",
            "create-question",
            "Orders",
            '{"database": 1, "type": "query", "query": {"source-table": 2}}',
            "--display",
            "table",
            "--visualization-settings",
            '{"table.pivot": false}',
            "--collection-id",
            "root",
            "--description",
            "Orders question",
        ],
    )

    assert result.exit_code == 0
    _assert_json_contains(result.stdout, {"method": "POST", "path": "/api/card"})
    assert _LAST_CALL["body"] == {
        "name": "Orders",
        "dataset_query": {"database": 1, "type": "query", "query": {"source-table": 2}},
        "display": "table",
        "visualization_settings": {"table.pivot": False},
        "type": "question",
        "collection_id": "root",
        "description": "Orders question",
    }


def test_create_card_command_preserves_card_type(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(cli.runtime, "create_client", lambda _settings: _ClientWithRequestMethods())

    result = runner.invoke(
        cli.app,
        [
            "--base-url",
            "http://localhost:3000",
            "--api-key",
            "abc",
            "create-card",
            "Orders",
            '{"database": 1, "type": "query", "query": {"source-table": 2}}',
            "--type",
            "model",
        ],
    )

    assert result.exit_code == 0
    assert _LAST_CALL["body"] == {
        "name": "Orders",
        "dataset_query": {"database": 1, "type": "query", "query": {"source-table": 2}},
        "display": "table",
        "visualization_settings": {},
        "type": "model",
    }


def test_create_card_command_rejects_non_object_dataset_query(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(cli.runtime, "create_client", lambda _settings: _ClientWithRequestMethods())

    result = runner.invoke(
        cli.app,
        [
            "--base-url",
            "http://localhost:3000",
            "--api-key",
            "abc",
            "create-card",
            "Orders",
            "[]",
        ],
    )

    assert result.exit_code != 0


def test_create_database_command_posts_json(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(cli.runtime, "create_client", lambda _settings: _ClientWithRequestMethods())

    result = runner.invoke(
        cli.app,
        [
            "--base-url",
            "http://localhost:3000",
            "--api-key",
            "abc",
            "create-database",
            "analytics",
            "postgres",
            "--details",
            '{"host": "db.local", "port": 5432}',
        ],
    )

    assert result.exit_code == 0
    _assert_json_contains(result.stdout, {"method": "POST", "path": "/api/database"})
    assert _LAST_CALL["body"] == {
        "name": "analytics",
        "engine": "postgres",
        "details": {"host": "db.local", "port": 5432},
    }


def test_create_database_command_invalid_details_fails(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(cli.runtime, "create_client", lambda _settings: _ClientWithRequestMethods())

    result = runner.invoke(
        cli.app,
        [
            "--base-url",
            "http://localhost:3000",
            "--api-key",
            "abc",
            "create-database",
            "analytics",
            "postgres",
            "--details",
            "{bad-json}",
        ],
    )

    assert result.exit_code != 0


def test_create_database_command_rejects_non_object_details(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(cli.runtime, "create_client", lambda _settings: _ClientWithRequestMethods())

    result = runner.invoke(
        cli.app,
        [
            "--base-url",
            "http://localhost:3000",
            "--api-key",
            "abc",
            "create-database",
            "analytics",
            "postgres",
            "--details",
            "[]",
        ],
    )

    assert result.exit_code != 0


def test_move_cards_command_rejects_non_object_body(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(cli.runtime, "create_client", lambda _settings: _ClientWithRequestMethods())

    result = runner.invoke(cli.app, ["--base-url", "http://localhost:3000", "--api-key", "abc", "move-cards", "[]"])

    assert result.exit_code != 0


def test_error_response_is_reported_as_json(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(cli.runtime, "create_client", lambda _settings: _ErrorClient())

    result = runner.invoke(
        cli.app,
        [
            "--base-url",
            "http://localhost:3000",
            "--api-key",
            "abc",
            "current-user",
        ],
    )

    assert result.exit_code == 1
    assert '"error": ' in result.stdout + result.stderr


def test_missing_api_key_fails_fast(monkeypatch: pytest.MonkeyPatch) -> None:
    def should_not_be_called(_settings: object) -> None:
        raise AssertionError("create_client should not be used when API key is missing")

    monkeypatch.setattr(cli.runtime, "create_client", should_not_be_called)

    result = runner.invoke(
        cli.app,
        [
            "--base-url",
            "http://localhost:3000",
            "current-user",
        ],
    )

    assert result.exit_code != 0
